CREATE TABLE deaths (
    iso_code VARCHAR(10),
    continent VARCHAR(50),
    location VARCHAR(100),
    date DATE,
    population BIGINT,
    total_cases BIGINT,
    new_cases BIGINT,
    new_cases_smoothed BIGINT,
    total_deaths BIGINT,
    new_deaths BIGINT,
    new_deaths_smoothed BIGINT,
    total_cases_per_million DOUBLE,
    new_cases_per_million DOUBLE,
    new_cases_smoothed_per_million DOUBLE,
    total_deaths_per_million DOUBLE,
    new_deaths_per_million DOUBLE,
    new_deaths_smoothed_per_million DOUBLE,
    reproduction_rate DOUBLE,
    icu_patients BIGINT,
    icu_patients_per_million DOUBLE,
    hosp_patients BIGINT,
    hosp_patients_per_million DOUBLE,
    weekly_icu_admissions BIGINT,
    weekly_icu_admissions_per_million DOUBLE,
    weekly_hosp_admissions BIGINT,
    weekly_hosp_admissions_per_million DOUBLE
);
